[package]
name = "nisshi-broker"
description = "Tansu Kafka API compatible broker"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["dynostore", "libsql", "postgres", "slatedb", "turso"]
dynostore = ["dep:nisshi-storage-dynostore"]
libsql = ["dep:nisshi-storage-sql", "nisshi-storage-sql/libsql"]
postgres = ["dep:nisshi-storage-sql", "nisshi-storage-sql/postgres"]
slatedb = ["dep:nisshi-storage-slatedb"]
turso = ["dep:nisshi-storage-sql", "nisshi-storage-sql/turso"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
console.workspace = true
futures.workspace = true
glob.workspace = true
http-body-util.workspace = true
humantime.workspace = true
hyper-util.workspace = true
hyper.workspace = true
indicatif.workspace = true
jsonschema.workspace = true
libc.workspace = true
nisshi-auth.workspace = true
nisshi-model.workspace = true
nisshi-otel.workspace = true
nisshi-sans-io.workspace = true
nisshi-schema.workspace = true
nisshi-service.workspace = true
nisshi-storage-dynostore = { workspace = true, optional = true }
nisshi-storage-null.workspace = true
nisshi-storage-slatedb = { workspace = true, optional = true }
nisshi-storage-sql = { workspace = true, optional = true }
nisshi-storage.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
rama.workspace = true
rand.workspace = true
regex.workspace = true
rsasl.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
socket2.workspace = true
thiserror.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
assert_matches.workspace = true
object_store.workspace = true
rcgen.workspace = true
tempfile.workspace = true
pretty_assertions.workspace = true
slatedb.workspace = true
nisshi-schema.workspace = true
nisshi-storage.workspace = true
